west2-online/fzuhelper-server

.github/workflows/golangci-lint.yaml
fix: update the version of golangci-lint
=> fix: update the version of golangci-lint

cmd/api/main.go, cmd/classroom/main.go, pkg/client/rpc.go, pkg/logger/output.go
=> abstract the init of rpc client

cmd/course/dal/db/init.go, cmd/course/dal/db/user_course.go, cmd/course/dal/init.go, cmd/course/handler.go, cmd/course/main.go, cmd/course/service/get_course_list.go, cmd/user/service/get_logindata.go, config/sql/init.sql, docker/docker-compose.yml, go.mod, go.sum, pkg/constants/constants.go, pkg/utils/json.go, pkg/utils/utils.go
=> Add storage of course schedule

api/router/api/middleware.go
=> add calling middleware in academic

api/router/custom_router.go
=> feat: add login verification code compatibility

api/handler/api/user_service.go
不要问我为什么一直在fix，因为Android代码太乱了老找不到，测了才知道哪里有问题
=> fix: login verify response compatibility

internal/launch_screen/service/create_image.go, internal/launch_screen/service/update_image_property.go, pkg/db/launch_screen/get_image.go
=> fix:timestamp bug in launch_screen

Makefile, api/rpc/classroom_test.go, api/rpc/course_test.go, api/rpc/user_test.go
chore
补充在 #116 中没有添加的 test license header，同时在 Makefile 中的 verify 方法添加 license 检查
=> chore: add missing license header, update Makefile

api/middleware/jwt.go, api/model/api/api.go, api/router/api/api.go, api/router/api/middleware.go, idl/api.thrift
refactor
主要做的修改如下：
1. 对应重构服务的 URL，如果有大写全部替换为了小写
2. 变量命名采用 '-' 进行了分割
3. 重构后在本地进行了测试，发现 AccessToken 需要加上 ‘Bearer ’ 前缀才能被正常识别，所以为了方便测试，直接在代码层面直接加上了前缀
4. 重构的识别验证码服务原本有 'jwch' 前缀（鉴权），将其删除了 'jwch' 前缀
5. 登录服务为后端内部测试接口，添加了 'internal' 前缀
=> [BREAKING CHANGE] refactor: standardize url format and add prefix in accessToken

.codecov.yml, internal/paper/service/get_dir_test.go
查看上传的coverage.txt 发现测试报告的格式是 github.com/west2-online/fzuhelper-server/xxx，所以现在的codecov.yml 的ignore 是无效的
=> fix: codecov ignore not work

pkg/logger/output.go
=> fix: fix bug when output some log

pkg/db/course/create_course_test.go, pkg/db/course/get_course_test.go, pkg/db/course/update_course_test.go, pkg/db/launch_screen/add_image_list_showtime_test.go, pkg/db/launch_screen/add_point_time_test.go, pkg/db/launch_screen/create_image_test.go, pkg/db/launch_screen/delete_image_test.go, pkg/db/launch_screen/get_image_test.go, pkg/db/launch_screen/update_image_test.go
=> feat: add test in db

.github/workflows/deploy.yaml
=> ci: add version and common service auto deploy

api/model/model/model.go, idl/model.thrift, kitex_gen/model/k-model.go, kitex_gen/model/model.go
=> fix: replace optional with required in paper

.github/workflows/deploy.yaml
- 修改 cd 中 deploy 阶段的并发程度，使得不同的 service 之间是串行执行的，后续的 deploy workflow 将处于 pending
=> fix: modify cd concurency config

api/handler/api/user_service.go
规避前端的 Axios 响应拦截器，适配标准的格式（code、message）的 ping
=> chore: modify test auth respose

api/model/model/model.go, api/router/api/middleware.go, config/sql/init.sql, go.mod, go.sum, idl/model.thrift, internal/user/pack/info.go, internal/user/service/get_info.go, kitex_gen/model/k-model.go, kitex_gen/model/model.go, pkg/db/model/user.go, pkg/errno/default.go
=> feat: name filed in UserInfo

.github/workflows/deploy.yaml
- 在远程服务器上创建了对应的 `github-action-user`用户和`github-action`用户组，将部署所使用到的文件夹 hack, docker, config移动到`/home/srv`下，并设置了对应的权限（只有 github-action 用户组才能访问）
- 原本想直接使用 `/srv`文件夹，但是这个文件夹似乎是阿里云服务器自带的，为了做区别所以创建了`/home/srv`
- 对应的 github secret 也已经做了修改，不再使用 root 用户的密钥
- 对应密钥的管理，似乎还有`github App`，我大致了解了一下，发现还挺麻烦的，链接放在这里供参考：https://docs.github.com/zh/authentication/connecting-to-github-with-ssh/managing-deploy-keys#github-app-%E5%AE%89%E8%A3%85%E8%AE%BF%E9%97%AE%E4%BB%A4%E7%89%8C
=> fix: modify deploy file location

cmd/common/main.go, internal/classroom/handler.go, internal/classroom/service/get_exam_room.go, internal/classroom/service/get_exam_room_test.go, internal/common/handler.go, internal/common/service/service.go, internal/common/service/term.go, internal/common/service/term_test.go, internal/paper/service/get_dir.go, pkg/cache/cache.go, pkg/cache/classroom/get_exam_room.go, pkg/cache/classroom/set_exam_room.go, pkg/cache/common/common.go, pkg/cache/common/get_term_info.go, pkg/cache/common/set_term_info.go, pkg/cache/common/util.go, pkg/cache/paper/set_file_dir.go, pkg/constants/redis.go
加缓存到考场和学期信息
exam room
term info
=> feat: add cache in term and exam room info

cmd/academic/main.go, internal/academic/handler.go, internal/academic/service/get_scores.go, internal/academic/service/get_scores_test.go, internal/academic/syncer/task.go, internal/academic/syncer/workqueue.go, pkg/cache/academic/set_scores.go, pkg/constants/constants.go
使用k8s workqueue 处理 setcache操作进行限流 ，避免 unpected 的大量 goroutine 调用
目前 classroom 的限流器初始化不规范，示例的acdemic模块使用了默认限流器
=> feat: use k8s workqueue instead of goroutines

go.mod, go.sum
=> fix: return empty slice when examroom is empty

go.mod, go.sum
=> chore: upgrade jwch to v0.2.9

api/model/model/model.go, api/pack/academic.go, idl/model.thrift, internal/academic/pack/score.go, kitex_gen/model/k-model.go, kitex_gen/model/model.go
=> feat: add score elective type field

internal/academic/service/get_plan.go
=> fix: return url format in getCultivatePlan

api/handler/api/academic_service_test.go, cmd/academic/main.go, cmd/course/main.go, internal/academic/handler.go, internal/academic/service/get_scores.go, internal/academic/service/get_scores_test.go, internal/academic/service/service.go, internal/course/handler.go, internal/course/service/get_course_list.go, internal/course/service/get_course_list_test.go, internal/course/service/get_terms_test.go, internal/course/service/service.go, internal/version/service/download_apk_test.go, pkg/cache/course/set_courses.go, pkg/cache/course/set_terms.go, pkg/constants/constants.go, pkg/constants/redis.go, pkg/syncer/syncer.go, pkg/syncer/task.go, pkg/taskqueue/model/academic.go, pkg/taskqueue/model/course.go, pkg/taskqueue/queue.go
将syncer抽象成task queue，基本是个线程池
接入了academic 和course
待更新其他模块
=> refactor: abstract syncer into task queue interface

internal/academic/pack/score.go
Resolves https://github.com/west2-online/jwch/issues/28.
=> refactor: add score mask

internal/course/pack/course.go
=> refactor: add course location mask

pkg/db/launch_screen/get_image.go
修正 GetImage 接口没有添加 Table 导致的 50001 内部错误
=> fix(launch-screen): GetImage not set table

go.mod, go.sum
=> fix: update nil pointer in get scores

pkg/db/notice/get_notice.go
=> fix: change the order of query notices

.golangci.yml, cmd/academic/main.go, config/sql/init.sql, internal/academic/service/get_scores.go, internal/academic/service/service.go, internal/academic/task_model/task_model.go, pkg/constants/constants.go, pkg/constants/db.go, pkg/db/academic/academic.go, pkg/db/academic/create_course_offering.go, pkg/db/academic/create_scores.go, pkg/db/academic/get_course_offering.go, pkg/db/academic/get_scores.go, pkg/db/academic/update_scores.go, pkg/db/db.go, pkg/db/model/academic.go, pkg/taskqueue/model/course.go, pkg/utils/jwch.go
使用友盟推送通道实现成绩推送功能
接口流程图
前端注意：推送成绩标识tag由md5编码，源码如下
```
tag := utils.MD5(strings.Join([]string{
t.scores[i].Name, t.scores[i].Semester, t.scores[i].Teacher,
t.scores[i].ElectiveType,
}, "|"))
func MD5(str string) string {
h := md5.New()
h.Write([]byte(str))
return hex.EncodeToString(h.Sum(nil))
}
```
=> feat: add score updated notice

go.mod, go.sum, internal/academic/service/get_plan.go
=> fix: jwch update

go.mod, go.sum
=> build: jwch update

internal/classroom/handler.go, pkg/constants/constants.go, pkg/constants/db.go, pkg/constants/jwch.go, pkg/constants/redis.go, pkg/constants/syncer.go, pkg/constants/time.go, pkg/constants/umeng.go
=> chore: format constants

pkg/base/options.go
chore
我们在日志中添加 Options 创建成功的日志
=> chore: add create success msg for options in base

.github/workflows/deploy.yaml
=> ci: update deploy.yaml

internal/academic/task_model/task_model.go, pkg/taskqueue/model/course.go
fix
去除多余的`utils.ParseJwchStuId`调用
=> fix: useless parse stuid

go.mod, go.sum
=> chore: update yjsy version

go.mod, go.sum, internal/academic/service/get_scores_test.go, internal/classroom/handler.go, internal/classroom/pack/exam_room_info.go, internal/classroom/service/get_exam_room.go, internal/classroom/service/get_exam_room_test.go, internal/user/handler.go, internal/user/service/get_info.go, pkg/base/pack.go, pkg/cache/classroom/get_exam_room.go, pkg/cache/classroom/set_exam_room.go
接口增加研究生获取考场和获取用户信息
考场的缓存优化了参数，使用kitex model 而不是jwch model,使得研究生和本科生使用同一套cache函数
=> feat: yjsy get user info && get exam room

api/handler/api/user_service.go
=> fix: select semeter not align for postgraduate

go.mod, go.sum
=> chore: update yjsy

pkg/constants/syncer.go
=> chore: add explaination for contributor urls

internal/common/pack/contributor.go, pkg/constants/syncer.go
=> fix: import

go.mod, go.sum, internal/common/pack/term.go
=> fix: nil pointer in calendar

cmd/api/main.go
=> fix: add the Threshold of sentinel to 5000

cmd/version/main.go, config/sql/init.sql, internal/version/handler.go, internal/version/service/download_apk.go, internal/version/service/get_dump.go, internal/version/service/get_setting.go, internal/version/service/service.go, internal/version/task_model/task_model.go, pkg/cache/cache.go, pkg/cache/version/add_visit.go, pkg/cache/version/get_visit.go, pkg/cache/version/version.go, pkg/constants/constants.go, pkg/constants/db.go, pkg/constants/redis.go, pkg/db/db.go, pkg/db/model/version.go, pkg/db/version/create_version.go, pkg/db/version/get_version.go, pkg/db/version/version.go, pkg/taskqueue/queue.go
使用redis Incr+定时workqueue存储mysql来替代之前的读取更改存入云端的操作
=> feat: revise the logic of version.visitsdump

internal/course/pack/course.go
=> fix: course without remark

docker/Dockerfile
=> fix: goproxy in Dockerfile

pkg/cache/course/get_courses.go
=> fix: get course no pointer

cmd/common/main.go, internal/academic/handler.go, internal/course/handler.go
=> chore: log clean

pkg/cache/cache.go
=> fix: get locate date marshal error

internal/course/service/get_calendar.go
=> fix: adjust course name of exported calendar

internal/course/service/get_date.go
=> fix: optimize locate date

cmd/course/main.go, internal/course/handler.go, internal/course/service/get_calendar.go, internal/course/service/get_term_info.go, internal/course/service/service.go, pkg/base/clientset.go, pkg/base/options.go, pkg/constants/location.go, pkg/constants/token.go
- 从 jwc 获取开学日期 --> 通过调用 common rpc 获取开学日期
- 增加日历 description 和 location
=> feat: adding common rpc

go.mod, go.sum, internal/course/service/get_date.go, internal/course/service/get_date_test.go
=> update jwch version to v0.2.17

internal/course/service/get_date_test.go, internal/course/service/get_term_info.go
- 修改调用 common 的 rpc 调用，改成调用 termList，之前调用成学期信息了
- 本地测试过了，时间修正回来了
=> fix: revise calling rpc

api/router/api/middleware.go, cmd/course/main.go, internal/course/service/get_date.go, pkg/constants/redis.go, pkg/constants/syncer.go
=> fix: optimize locate date login 

internal/course/service/get_calendar.go
=> fix: event alarm of exported calendar

api/handler/api/user_service.go
- 使用闭包处理 http response body close 的错误
=> fix: close http client body

pkg/logger/mysql.go
- 修改 mysql 慢查询日志输出等级，方便日志观看（绿色是 info 级别，黄色是 warn 级别）
=> fix: change mysql logger print

api/mw/token.go, api/mw/token_test.go, go.mod, go.sum
更新 yjsy 版本，修复了 cookie 过期的识别不准确，现在可以返回正确错误码
=> fix: update yjsy version to fix cookie expire judge error

internal/course/service/get_calendar.go
=> 修正单双周课程的起始周数

cmd/common/main.go, pkg/db/notice/is_notice_exists.go
- 改用 title 作为 notice 的唯一索引，因为教务处后期可能会对url 进行改动
=> fix: the problem of duplicated notices

.github/workflows/deploy.yaml
=> feat: update cd temporarily

.github/workflows/deploy.yaml, docker/script/entrypoint.sh, ingress-nginx.yaml, k8s/README.md, k8s/fzuhelper-server/templates/deployment/service.yaml, k8s/fzuhelper-server/values.yaml
=> chore: recover ci 

api/handler/api/course_service.go
- 之前生成 token 时，忘记给 logindata中的 id 进行 trim 了。不知道对研究生的课程有没有影响，没有测试账号
=> fix: modify token created

config/config.go
修复代码会错误的覆盖掉etcd addr，导致获取不到config直接报错的问题
=> fix: etcd config load

.github/workflows/deploy.yaml
=> fix: recover deployment

internal/classroom/service/get_exam_room.go, pkg/constants/redis.go
=> fix: set cache expire time in exam room

go.mod
- 修改教务处url格式，具体参考jwch库
- 等 jwch 库 merge 后再操作
=> fix: sync for jwch

go.mod, go.sum, internal/academic/service/get_scores_test.go
=> refactor: update proxy model

go.mod, go.sum
=> chore: update jwch

docker/Dockerfile
chore: update go in dockerfile
chore: update go in dockerfile
=> chore: update go in dockerfile

go.mod, go.sum
=> chore: update yjsy to v0.0.9

internal/launch_screen/pack/image.go
=> fix: 开屏页返回值
